[package]
name = "maxRugTracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
rusqlite = "0.36.0"
serde = "1.0.219"
serde_json = "1.0.140"
serve = "0.0.1"
tungstenite = "0.26.2"
